//src/app/layout.tsx
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import Main from "./_components/Main";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Dev.to Clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo_devto.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <Main>{children}</Main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
